#! /usr/bin/env python

import sys
import os
import sipconfig
import subprocess

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "pypcie.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
sipcmd = [config.sip_bin]
sipcmd.extend(["-c", "."])
sipcmd.extend(["-I", "."])
sipcmd.extend(["-b", build_file])
sipcmd.extend(["python-pcie.sip"])
#os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "python-pcie.sip"]))
print " ".join(sipcmd)
result = subprocess.call(sipcmd)
if result != 0:
    sys.exit(result)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_lib_dirs = [os.path.join(os.path.pardir, "lib")]
makefile.extra_libs = ["pypcie"]

# Generate the Makefile itself.
makefile.generate()
