/*
 * Internal module API header file.
 *
 * Generated by SIP 4.16.9
 */

#ifndef _pcieAPI_H
#define _pcieAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_close_pcie 0
#define sipName_close_pcie &sipStrings_pcie[0]
#define sipNameNr_PythonPCIE 11
#define sipName_PythonPCIE &sipStrings_pcie[11]
#define sipNameNr_open_pcie 22
#define sipName_open_pcie &sipStrings_pcie[22]
#define sipNameNr_uint64_t 32
#define sipName_uint64_t &sipStrings_pcie[32]
#define sipNameNr_uint8_t 41
#define sipName_uint8_t &sipStrings_pcie[41]
#define sipNameNr_is_open 49
#define sipName_is_open &sipStrings_pcie[49]
#define sipNameNr_write 57
#define sipName_write &sipStrings_pcie[57]
#define sipNameNr_read 63
#define sipName_read &sipStrings_pcie[63]
#define sipNameNr_pcie 6
#define sipName_pcie &sipStrings_pcie[6]

#define sipMalloc                   sipAPI_pcie->api_malloc
#define sipFree                     sipAPI_pcie->api_free
#define sipBuildResult              sipAPI_pcie->api_build_result
#define sipCallMethod               sipAPI_pcie->api_call_method
#define sipCallErrorHandler         sipAPI_pcie->api_call_error_handler
#define sipParseResultEx            sipAPI_pcie->api_parse_result_ex
#define sipParseResult              sipAPI_pcie->api_parse_result
#define sipParseArgs                sipAPI_pcie->api_parse_args
#define sipParseKwdArgs             sipAPI_pcie->api_parse_kwd_args
#define sipParsePair                sipAPI_pcie->api_parse_pair
#define sipCommonDtor               sipAPI_pcie->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_pcie->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_pcie->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_pcie->api_convert_to_void_ptr
#define sipAddException             sipAPI_pcie->api_add_exception
#define sipNoFunction               sipAPI_pcie->api_no_function
#define sipNoMethod                 sipAPI_pcie->api_no_method
#define sipAbstractMethod           sipAPI_pcie->api_abstract_method
#define sipBadClass                 sipAPI_pcie->api_bad_class
#define sipBadCatcherResult         sipAPI_pcie->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_pcie->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_pcie->api_bad_operator_arg
#define sipTrace                    sipAPI_pcie->api_trace
#define sipTransferBack             sipAPI_pcie->api_transfer_back
#define sipTransferTo               sipAPI_pcie->api_transfer_to
#define sipTransferBreak            sipAPI_pcie->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_pcie->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_pcie->api_wrapper_type
#define sipWrapperType_Type         sipAPI_pcie->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_pcie->api_voidptr_type
#define sipGetPyObject              sipAPI_pcie->api_get_pyobject
#define sipGetAddress               sipAPI_pcie->api_get_address
#define sipGetMixinAddress          sipAPI_pcie->api_get_mixin_address
#define sipGetCppPtr                sipAPI_pcie->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_pcie->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_pcie->api_is_py_method
#define sipCallHook                 sipAPI_pcie->api_call_hook
#define sipEndThread                sipAPI_pcie->api_end_thread
#define sipConnectRx                sipAPI_pcie->api_connect_rx
#define sipDisconnectRx             sipAPI_pcie->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_pcie->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_pcie->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_pcie->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_pcie->api_add_type_instance
#define sipFreeSipslot              sipAPI_pcie->api_free_sipslot
#define sipSameSlot                 sipAPI_pcie->api_same_slot
#define sipPySlotExtend             sipAPI_pcie->api_pyslot_extend
#define sipConvertRx                sipAPI_pcie->api_convert_rx
#define sipAddDelayedDtor           sipAPI_pcie->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_pcie->api_can_convert_to_type
#define sipConvertToType            sipAPI_pcie->api_convert_to_type
#define sipForceConvertToType       sipAPI_pcie->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_pcie->api_can_convert_to_enum
#define sipReleaseType              sipAPI_pcie->api_release_type
#define sipConvertFromType          sipAPI_pcie->api_convert_from_type
#define sipConvertFromNewType       sipAPI_pcie->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_pcie->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_pcie->api_convert_from_enum
#define sipGetState                 sipAPI_pcie->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_pcie->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_pcie->api_export_symbol
#define sipImportSymbol             sipAPI_pcie->api_import_symbol
#define sipFindType                 sipAPI_pcie->api_find_type
#define sipFindNamedEnum            sipAPI_pcie->api_find_named_enum
#define sipBytes_AsChar             sipAPI_pcie->api_bytes_as_char
#define sipBytes_AsString           sipAPI_pcie->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_pcie->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_pcie->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_pcie->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_pcie->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_pcie->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_pcie->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_pcie->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_pcie->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_pcie->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_pcie->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_pcie->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_pcie->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_pcie->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_pcie->api_save_slot
#define sipClearAnySlotReference    sipAPI_pcie->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_pcie->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_pcie->api_deprecated
#define sipGetReference             sipAPI_pcie->api_get_reference
#define sipKeepReference            sipAPI_pcie->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_pcie->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_pcie->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_pcie->api_type_from_py_type_object
#define sipTypeScope                sipAPI_pcie->api_type_scope
#define sipResolveTypedef           sipAPI_pcie->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_pcie->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_pcie->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_pcie->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_pcie->api_enable_autoconversion
#define sipInitMixin                sipAPI_pcie->api_init_mixin
#define sipExportModule             sipAPI_pcie->api_export_module
#define sipInitModule               sipAPI_pcie->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_pcie->api_map_string_to_class
#define sipMapIntToClass            sipAPI_pcie->api_map_int_to_class
#define sipFindClass                sipAPI_pcie->api_find_class
#define sipFindMappedType           sipAPI_pcie->api_find_mapped_type
#define sipConvertToArray           sipAPI_pcie->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_pcie->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_pcie->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_pcie[];

#define sipType_PythonPCIE              sipModuleAPI_pcie.em_types[0]
#define sipClass_PythonPCIE             sipModuleAPI_pcie.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_pcie_PythonPCIE;

#define sipType_uint8_t      sipModuleAPI_pcie.em_types[2]

extern sipMappedTypeDef sipTypeDef_pcie_uint8_t;

#define sipType_uint64_t      sipModuleAPI_pcie.em_types[1]

extern sipMappedTypeDef sipTypeDef_pcie_uint64_t;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_pcie;
extern sipExportedModuleDef sipModuleAPI_pcie;

#endif
