/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.17
 */

#include "sipAPIpcie.h"

#line 33 "python-pcie.sip"
#include <stdint.h>
#line 12 "./sippcieuint64_t.cpp"



extern "C" {static void assign_uint64_t(void *, SIP_SSIZE_T, const void *);}
static void assign_uint64_t(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<uint64_t *>(sipDst)[sipDstIdx] = *reinterpret_cast<const uint64_t *>(sipSrc);
}


extern "C" {static void *array_uint64_t(SIP_SSIZE_T);}
static void *array_uint64_t(SIP_SSIZE_T sipNrElem)
{
    return new uint64_t[sipNrElem];
}


extern "C" {static void *copy_uint64_t(const void *, SIP_SSIZE_T);}
static void *copy_uint64_t(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new uint64_t(reinterpret_cast<const uint64_t *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_uint64_t(void *, int);}
static void release_uint64_t(void *ptr, int)
{
    delete reinterpret_cast<uint64_t *>(ptr);
}



extern "C" {static int convertTo_uint64_t(PyObject *, void **, int *, PyObject *);}
static int convertTo_uint64_t(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *)
{
    uint64_t **sipCppPtr = reinterpret_cast<uint64_t **>(sipCppPtrV);

#line 43 "python-pcie.sip"
    if (sipIsErr == NULL)
    {
        return (PyInt_Check(sipPy));
    }

    if (sipPy == Py_None)
    {
        *sipCppPtr = new uint64_t();
        return 1;
    }

    if (PyInt_Check(sipPy))
    {
        *sipCppPtr = new uint64_t(PyInt_AS_LONG(sipPy));
        return 1;
    }
    return 0;
#line 69 "./sippcieuint64_t.cpp"
}


extern "C" {static PyObject *convertFrom_uint64_t(void *, PyObject *);}
static PyObject *convertFrom_uint64_t(void *sipCppV, PyObject *)
{
   uint64_t *sipCpp = reinterpret_cast<uint64_t *>(sipCppV);

#line 37 "python-pcie.sip"
    PyObject* pSize;
    pSize = PyLong_FromSize_t(*sipCpp);
    return pSize;
#line 82 "./sippcieuint64_t.cpp"
}


sipMappedTypeDef sipTypeDef_pcie_uint64_t = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_uint64_t,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_uint64_t,
    array_uint64_t,
    copy_uint64_t,
    release_uint64_t,
    convertTo_uint64_t,
    convertFrom_uint64_t
};
